variable "region" {}
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "vcn_name_a" {}
variable "vcn_name_b" {}
variable "cidr_block_vcn_a" {}
variable "cidr_block_vcn_b" {}
variable "compartment_id" {}
variable "subnet_a_cidr_block" {}
variable "subnet_b_cidr_block" {}
variable "subnet_a_display_name" {}
variable "subnet_b_display_name" {}
variable "route_table_display_name_a" {}
variable "route_table_display_name_b" {}
variable "internet_gateway_display_name_a" {}
variable "internet_gateway_display_name_b" {}
variable "local_peering_gateway_display_name_a" {}
variable "local_peering_gateway_display_name_b" {}
variable "open_to_the_world" {}
variable "security_list_name_a" {}
variable "security_list_name_b" {}